ALTER TABLE book ADD UNIQUE (title);
ALTER TABLE book MODIFY COLUMN summary VARCHAR(500) NOT NULL;
ALTER TABLE book MODIFY COLUMN number_of_pages INT NOT NULL;
ALTER TABLE book MODIFY COLUMN category VARCHAR(70) NOT NULL;

